#!/bin/sh
export AWS_DEFAULT_REGION="WHERE IS EKS DEPLOYED?"
export CACHE_BUCKET_NAME="CI CACHE BUCKET"
export CUR_BUCKET_NAME="CUR BUCKET"
export RESULTS_BUCKET_NAME="BILLING RESULTS BUCKET"

export CW_CLUSTER_LOGS="/aws/eks/ci-cluster/cluster"
export CW_VPC_FLOW_LOGS="vpc-flow-logs"

export AUTH0_CLIENT_AUDIENCE="NOT NEEDED IF NOT USING CODELINARO"
export AUTH0_CLIENT_URL="NOT NEEDED IF NOT USING CODELINARO"
export CLO_API_URL="NOT NEEDED IF NOT USING CODELINARO"
export GITLAB_URL="NOT NEEDED IF NOT USING CODELINARO"
export SECRET_NAME="NOT NEEDED IF NOT USING CODELINARO"
# Use -u to unbuffer the output so that it appears in the logs promptly
python -u billing_analysis.py
