name: push-main

on:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/pullrequest.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Fetch git repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube quality check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Cleanup scan
        run: sudo rm -rf "$GITHUB_WORKSPACE/.scannerwork"
